[build]
  command = "npm run build"
  publish = "web/"
  functions = "functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "#custom"

[context.deploy-preview]
  command = "npm run build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
      Referrer-Policy = "strict-origin-when-cross-origin"


[[redirects]]
  from = "/dotaznik"
  to = "https://forms.gle/YpCbDNyC3vHutJd37"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/discord"
  to = "https://www.discord.com/invite/A9sKuZzzya"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/prihlaseni-prednasky"
  to = "https://forms.gle/TAyjxZH9YHn8YmKV7"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404