[build]
  command = "npm run build"
  publish = "web/"
  functions = "functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "#custom"

[context.deploy-preview]
  command = "npm run build"

[[redirects]]
  from = "/dotaznik"
  to = "https://forms.gle/YpCbDNyC3vHutJd37"
  status = 200
  force = true