[build]
  command = "npm run build"
  publish = "web/"
  functions = "functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "#custom"

[context.deploy-preview]
  command = "npm run build"