(function(g){var window=this;var dqa=function(a,b){return g.Vb(a,b)},e5=function(a,b,c){a.l.set(b,c)},f5=function(a){e5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},g5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.Um(a.l,b,c)},eqa=function(a,b){var c=[];
g.Yi(b,function(d){try{var e=g.Zn.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.Yn(e)&&c.push(d):c.push(d)},a);
return c},fqa=function(a,b){var c=eqa(a,b);
(0,g.z)(c,function(d){g.Zn.prototype.remove.call(this,d)},a)},h5=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},gqa=function(a,b){g.ab(a,b)||a.push(b)},i5=function(a){var b=0,c;
for(c in a)b++;return b},j5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},k5=function(){},hqa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},iqa=function(a){if(a.Ec&&"function"==typeof a.Ec)return a.Ec();
if(g.u(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},jqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.u(a))(0,g.z)(a,b,void 0);else{if(a.Pd&&"function"==typeof a.Pd)var c=a.Pd();else if(a.Ec&&"function"==typeof a.Ec)c=void 0;else if(g.La(a)||g.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=iqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},kqa=function(a,b,c,d){var e=new g.Im(null,void 0);
a&&g.Jm(e,a);b&&g.Km(e,b);c&&g.Lm(e,c);d&&(e.i=d);return e},l5=function(a,b){g.bp[a]=!0;
var c=g.$o();c&&c.publish.apply(c,arguments);g.bp[a]=!1},m5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Fm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",lqa(this,a.capabilities||""),mqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},lqa=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.Qa(dqa,nqa)).forEach(function(c){a.capabilities.add(c)})},mqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},n5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},o5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},p5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},oqa=function(a){return new n5(a)},q5=function(a){return g.Ka(a)?(0,g.B)(a,oqa):[]},r5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},s5=function(a){return g.Ka(a)?"["+(0,g.B)(a,r5).join(",")+"]":"null"},t5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},pqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},u5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},v5=function(a,b){return g.Ya(a,function(c){return o5(c,b)})},w5=function(a){try{var b=(0,g.As)(),c=(0,g.zs)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},qqa=function(){var a=(0,g.zs)();
a&&fqa(a,a.g.mf(!0))},x5=function(){var a=g.Cs("yt-remote-connected-devices")||[];
g.qb(a);return a},rqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},y5=function(a){g.Bs("yt-remote-connected-devices",a,86400)},A5=function(){if(z5)return z5;
var a=g.Cs("yt-remote-device-id");a||(a=t5(),g.Bs("yt-remote-device-id",a,31536E3));for(var b=x5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return z5=d},B5=function(){var a=x5(),b=A5();
g.ab(a,b);g.Ds()&&g.sb(a,b);a=rqa(a);if(0==a.length)try{g.yr("remote_sid")}catch(c){}else try{g.xr("remote_sid",a.join(","),-1)}catch(c){}},C5=function(){return g.Cs("yt-remote-session-browser-channel")},D5=function(){return g.Cs("yt-remote-local-screens")||[]},E5=function(){g.Bs("yt-remote-lounge-token-expiration",!0,86400)},sqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(D5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.eh)(c,function(d){return!g.ab(b,d)})&&E5();
g.Bs("yt-remote-local-screens",a,31536E3)},tqa=function(a,b){g.Bs("yt-remote-session-browser-channel",a);
g.Bs("yt-remote-session-screen-id",b);var c=x5(),d=A5();g.ab(c,d)||c.push(d);y5(c);B5()},F5=function(a){a||(w5("yt-remote-session-screen-id"),w5("yt-remote-session-video-id"));
B5();a=x5();g.db(a,A5());y5(a)},H5=function(){if(!G5){var a=g.jo();
a&&(G5=new g.Tn(a))}return G5?!!G5.get("yt-remote-use-staging-server"):!1},I5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},J5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},L5=function(a){a.length?K5(a.shift(),function(){L5(a)}):M5()},uqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},K5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},M5=function(){var a=J5();
a&&a(!1,"No cast extension found")},N5=function(){if(vqa){var a=2,b=J5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;K5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",M5,c)}},wqa=function(){N5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);L5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},O5=function(a,b,c){g.H.call(this);
this.B=null!=c?(0,g.y)(a,c):a;this.Xc=b;this.A=(0,g.y)(this.oD,this);this.g=!1;this.i=0;this.l=this.Da=null;this.o=[]},P5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return hqa(a)},Q5=function(){},R5=function(){},S5=function(){},U5=function(a){return(a=T5(a))?new ActiveXObject(a):new XMLHttpRequest},T5=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},V5=function(a,b,c,d){this.g=a;
this.l=b;this.D=c;this.B=d||1;this.o=45E3;this.ca=new g.bY(this);this.i=new g.al;this.i.setInterval(250)},X5=function(a,b,c){a.Wh=1;
a.Wf=f5(b.clone());a.oh=c;a.A=!0;W5(a,null)},Y5=function(a,b,c,d,e){a.Wh=1;
a.Wf=f5(b.clone());a.oh=null;a.A=c;e&&(a.oA=!1);W5(a,d)},W5=function(a,b){a.Ci=(0,g.D)();
Z5(a);a.Ag=a.Wf.clone();g5(a.Ag,"t",a.B);a.dl=0;a.sc=a.g.Pp(a.g.Pk()?b:null);0<a.yq&&(a.Vn=new g.dl((0,g.y)(a.oB,a,a.sc),a.yq));a.ca.ea(a.sc,"readystatechange",a.hM);var c=a.Wg?g.cc(a.Wg):{};a.oh?(a.Eo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Ag,a.Eo,a.oh,c)):(a.Eo="GET",a.oA&&!g.Ld&&(c.Connection="close"),a.sc.send(a.Ag,a.Eo,null,c));a.g.ze(1)},f6=function(a,b,c){for(var d=!0;!a.Lg&&a.dl<c.length;){var e=xqa(a,c);
if(e==$5){4==b&&(a.ng=4,a6(15),d=!1);break}else if(e==b6){a.ng=4;a6(16);d=!1;break}else c6(a,e)}4==b&&0==c.length&&(a.ng=1,a6(17),d=!1);a.Ce=a.Ce&&d;d||(d6(a),e6(a))},xqa=function(a,b){var c=a.dl,d=b.indexOf("\n",c);
if(-1==d)return $5;c=Number(b.substring(c,d));if(isNaN(c))return b6;d+=1;if(d+c>b.length)return $5;var e=b.substr(d,c);a.dl=d+c;return e},i6=function(a,b){a.Ci=(0,g.D)();
Z5(a);var c=b?window.location.hostname:"";a.Ag=a.Wf.clone();e5(a.Ag,"DOMAIN",c);e5(a.Ag,"t",a.B);try{a.Ge=new ActiveXObject("htmlfile")}catch(n){d6(a);a.ng=7;a6(22);e6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in g6)k=g6[l];else if(l in h6)k=g6[l]=h6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
g6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.rc("b/12014412"),d+"</body></html>");a.Ge.open();a.Ge.write(g.Mc(c));a.Ge.close();a.Ge.parentWindow.m=(0,g.y)(a.xL,a);a.Ge.parentWindow.d=(0,g.y)(a.yz,a,!0);a.Ge.parentWindow.rpcClose=(0,g.y)(a.yz,a,!1);c=a.Ge.createElement("DIV");a.Ge.parentWindow.document.body.appendChild(c);d=g.Cc(a.Ag.toString());d=g.Yc(g.zc(d));d=g.Rc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.ze(1)},Z5=function(a){a.Bt=(0,g.D)()+a.o;
j6(a,a.o)},j6=function(a,b){if(null!=a.Si)throw Error("WatchDog timer not null");
a.Si=k6((0,g.y)(a.HL,a),b)},l6=function(a){a.Si&&(g.w.clearTimeout(a.Si),a.Si=null)},e6=function(a){a.g.ww()||a.Lg||a.g.Jn(a)},d6=function(a){l6(a);
g.Bi(a.Vn);a.Vn=null;a.i.stop();g.dY(a.ca);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.Ge&&(a.Ge=null)},c6=function(a,b){try{a.g.rz(a,b),a.g.ze(4)}catch(c){}},n6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;m6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){n6(a,b,c,d,f)},f)})}},m6=function(a,b,c){var d=new Image;
d.onload=function(){try{o6(d),c(!0)}catch(e){}};
d.onerror=function(){try{o6(d),c(!1)}catch(e){}};
d.onabort=function(){try{o6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{o6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
j5(d,a)},o6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},p6=function(a){this.g=a;
this.i=new Q5},r6=function(a){var b=q6(a.g,a.hj,"/mail/images/cleardot.gif");
f5(b);n6(b.toString(),5E3,(0,g.y)(a.vC,a),3,2E3);a.ze(1)},t6=function(a){var b=a.g.G;
if(null!=b)a6(5),b?(a6(11),s6(a.g,a,!1)):(a6(12),s6(a.g,a,!0));else if(a.Gd=new V5(a,void 0,void 0,void 0),a.Gd.Wg=a.wq,b=a.g,b=q6(b,b.Pk()?a.Mj:null,a.xq),a6(5),!g.Jd||g.md(10))g5(b,"TYPE","xmlhttp"),Y5(a.Gd,b,!1,a.Mj,!1);else{g5(b,"TYPE","html");var c=a.Gd;a=!!a.Mj;c.Wh=3;c.Wf=f5(b.clone());i6(c,a)}},u6=function(a){g.qk.call(this);
this.headers=new g.Fm;this.N=a||null;this.i=!1;this.T=this.g=null;this.Z=this.F="";this.A=0;this.l="";this.o=this.aa=this.D=this.R=!1;this.B=0;this.G=null;this.X="";this.J=this.S=!1},yqa=function(a){return g.Jd&&g.kd(9)&&g.Fa(a.timeout)&&g.Da(a.ontimeout)},zqa=function(a){return"content-type"==a.toLowerCase()},x6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.A=5;v6(a);w6(a)},v6=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},A6=function(a){if(a.i&&"undefined"!=typeof g.hY)if(a.T[1]&&4==y6(a)&&2==a.getStatus())z6(a,"Local request error detected and ignored");
else if(a.D&&4==y6(a))g.bl(a.yw,0,a);else if(a.dispatchEvent("readystatechange"),4==y6(a)){z6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.tf(1,String(a.F));if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Aqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<y6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";v6(a)}}finally{w6(a)}}},w6=function(a,b){if(a.g){B6(a);
var c=a.g,d=a.T[0]?g.Ha:null;a.g=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},B6=function(a){a.g&&a.J&&(a.g.ontimeout=null);
a.G&&(g.w.clearTimeout(a.G),a.G=null)},y6=function(a){return a.g?a.g.readyState:0},C6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},z6=function(a,b){return b+" ["+a.Z+" "+a.F+" "+a.getStatus()+"]"},D6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.A=new Q5;this.F=a||null;this.G=null!=b?b:null;this.B=c||!1},Bqa=function(a,b){this.g=a;
this.map=b;this.context=null},E6=function(a){g.Sj.call(this,"statevent",a)},F6=function(a,b){g.Sj.call(this,"timingevent",a);
this.size=b},G6=function(a){g.Sj.call(this,"serverreachability",a)},K6=function(a){H6(a);
if(3==a.g){var b=a.vk++,c=a.hm.clone();e5(c,"SID",a.l);e5(c,"RID",b);e5(c,"TYPE","terminate");I6(a,c);b=new V5(a,a.l,b,void 0);b.Wh=2;b.Wf=f5(c.clone());j5(new Image,b.Wf.toString());b.Ci=(0,g.D)();Z5(b)}J6(a)},M6=function(a){a.NC(1,0);
a.hm=q6(a,null,a.uq);L6(a)},H6=function(a){a.dg&&(a.dg.abort(),a.dg=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.nf&&(g.w.clearTimeout(a.nf),a.nf=null);N6(a);a.Cd&&(a.Cd.cancel(),a.Cd=null);a.lg&&(g.w.clearTimeout(a.lg),a.lg=null)},O6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Bqa(a.LH++,b));2!=a.g&&3!=a.g||L6(a)},L6=function(a){a.Cd||a.lg||(a.lg=k6((0,g.y)(a.xz,a),0),a.Ph=0)},R6=function(a,b){if(1==a.g){if(!b){a.vk=Math.floor(1E5*Math.random());
var c=a.vk++,d=new V5(a,"",c,void 0);d.Wg=null;var e=P6(a),f=a.hm.clone();e5(f,"RID",c);e5(f,"CVER","1");I6(a,f);X5(d,f,e);a.Cd=d;a.g=2}}else 3==a.g&&(b?Q6(a,b):0==a.i.length||a.Cd||Q6(a))},Q6=function(a,b){if(b)if(6<a.Mg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.vk-1;var d=P6(a)}else c=b.D,d=b.oh;else c=a.vk++,d=P6(a);var e=a.hm.clone();e5(e,"SID",a.l);e5(e,"RID",c);e5(e,"AID",a.ji);I6(a,e);c=new V5(a,a.l,c,a.Ph+1);c.Wg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Cd=c;X5(c,e,d)},I6=function(a,b){if(a.Uc){var c=a.Uc.Uv();
c&&g.Kb(c,function(d,e){e5(b,e,d)})}},P6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Mg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Mg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},S6=function(a){a.Rb||a.nf||(a.D=1,a.nf=k6((0,g.y)(a.wz,a),0),a.Ih=0)},U6=function(a){if(a.Rb||a.nf||3<=a.Ih)return!1;
a.D++;a.nf=k6((0,g.y)(a.wz,a),T6(a,a.Ih));a.Ih++;return!0},s6=function(a,b,c){a.Co=c;
a.Le=b.Bf;a.B||M6(a)},N6=function(a){null!=a.Qg&&(g.w.clearTimeout(a.Qg),a.Qg=null)},T6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W6=function(a,b){if(2==b||9==b){var c=null;
a.Uc&&(c=null);var d=(0,g.y)(a.KM,a);c||(c=new g.Im("//www.google.com/images/cleardot.gif"),f5(c));m6(c.toString(),1E4,d)}else a6(2);V6(a,b)},V6=function(a,b){a.g=0;
a.Uc&&a.Uc.Tu(b);J6(a);H6(a)},J6=function(a){a.g=0;
a.Le=-1;if(a.Uc)if(0==a.o.length&&0==a.i.length)a.Uc.Cp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Uc.Cp(b)}},q6=function(a,b,c){var d=g.Qm(c);
if(""!=d.g)b&&g.Km(d,b+"."+d.g),g.Lm(d,d.A);else{var e=window.location;d=kqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.vj&&g.Kb(a.vj,function(f,k){e5(d,k,f)});
e5(d,"VER",a.Mg);I6(a,d);return d},k6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},a6=function(a){X6.dispatchEvent(new E6(X6,a))},Y6=function(){},Z6=function(){this.g=[];
this.i=[]},Cqa=function(a,b){this.action=a;
this.params=b||{}},$6=function(a,b){g.H.call(this);
this.g=new g.K(this.pL,0,this);g.J(this,this.g);this.Xc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},a7=function(a,b,c){this.I=a;
this.B=b;this.l=new g.Sn;this.i=new $6(this.rM,this);this.g=null;this.ib=!1;this.A=null;this.G="";this.F=this.o=0;this.D=[];this.J=c||!1},Dqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Co,sessionId:a.g.l,arrayId:a.g.ji}},b7=function(a,b){a.F=b||0;
a.i.stop();a.g&&(3==a.g.g&&R6(a.g),K6(a.g));a.F=0},c7=function(a){return!!a.g&&3==a.g.g},Eqa=function(a,b){(a.B.loungeIdToken=b)||a.i.stop()},d7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.tf(4,a))||"";b&&(this.port=":"+b);this.domain=g.uf(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},e7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ef(c+b,{})},f7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),oe:g.Qa(a.A,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Up(b,a)},Fqa=function(){var a=g7;
h7();i7.push(a);j7(i7)},k7=function(a,b){h7();
var c=i7,d=Gqa(a,String(b));0==c.length?Hqa(d):(j7(c),(0,g.z)(c,function(e){e(d)}))},h7=function(){i7||(i7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",i7,void 0))},Hqa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},j7=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},Gqa=function(a,b){var c=((0,g.D)()-Iqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.O.call(this);
this.D=a;this.g=[]},p7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Jqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Vd)(a.g,function(f){return!!u5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=p7(a,b[d])||c;return c},Kqa=function(a,b){var c=a.g.length;
a.g=(0,g.Vd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},q7=function(a,b,c,d){g.O.call(this);
this.B=a;this.A=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Da=NaN},s7=function(a){o7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;r7(this);this.info("Initializing with "+s5(this.g))},t7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=e7(a.l,"/pairing/get_lounge_token_batch");
f7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.zD,a),(0,g.y)(a.yD,a))}},r7=function(a){var b=q5(D5());
b=(0,g.Vd)(b,function(c){return!c.uuid});
return Jqa(a,b)},u7=function(a,b){sqa((0,g.B)(a.g,p5));
b&&E5()},w7=function(a,b){g.O.call(this);
this.B=b;var c=g.Cs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.B(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.A=a;this.l=this.o=NaN;this.i=null;v7("Initialized with "+g.rm(this.g))},x7=function(a,b,c){var d=e7(a.A,"/pairing/get_screen_availability");
f7(a.A,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},y7=function(a,b){a:if(i5(b)!=i5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(v7("Updated online screens: "+g.rm(a.g)),a.g=b,a.O("screenChange"));Lqa(a)},z7=function(a){isNaN(a.l)||g.Zo(a.l);
a.l=g.Xo((0,g.y)(a.Fs,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},v7=function(a){k7("OnlineScreenService",a)},A7=function(a){var b={};
(0,g.z)(a.B(),function(c){c.token?b[c.token]=c.id:this.Ib("Requesting availability of screen w/o lounge token.")});
return b},Lqa=function(a){a=g.Sb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Bs("yt-remote-online-screen-ids",a.join(","),60):w5("yt-remote-online-screen-ids")},B7=function(a){o7.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.o=[];this.A={};Mqa(this)},D7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.A[b]);var k=a.Qd();if(k=(c?v5(k,c):null)||v5(k,b)){k.uuid=b;var l=C7(a,k);x7(a.i,l,function(m){e(m?l:null)})}else c?Nqa(a,c,(0,g.y)(function(m){var n=C7(this,new n5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));x7(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},E7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Nqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Up(e7(a.B,"/pairing/get_lounge_token_batch"),e)},F7=function(a){a.g=a.l.Qd();
var b=a.A,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+s5(a.g))},Mqa=function(a){G7(a);
a.l=new s7(a.B);a.l.subscribe("screenChange",(0,g.y)(a.HD,a));F7(a);a.o=q5(g.Cs("yt-remote-automatic-screen-cache")||[]);G7(a);a.info("Initializing automatic screens: "+s5(a.o));a.i=new w7(a.B,(0,g.y)(a.Qd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.O("onlineScreenChange")},a))},C7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=v5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Bs("yt-remote-automatic-screen-cache",(0,g.B)(a.o,p5)));G7(a);a.A[b.uuid]=b.id;g.Bs("yt-remote-device-id-map",a.A,31536E3);return b},G7=function(a){a.A=g.Cs("yt-remote-device-id-map")||{}},H7=function(a,b,c){g.O.call(this);
this.T=c;this.G=a;this.i=b;this.l=null},I7=function(a,b){k7(a.T,b)},K7=function(a,b){H7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.B=(0,g.y)(this.rN,this);this.A=(0,g.y)(this.SL,this);this.o=g.Xo((0,g.y)(function(){J7(this,null)},this),12E4)},Oqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.rm(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.y)(function(){I7(this,"Failed to send message: getMdxSessionStatus.")},a)):I7(a,"Sending yt message without session: "+g.rm(b))},J7=function(a,b){g.Zo(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Ln,a),d=(0,g.y)(a.Td,a);a.mw(b,c,d,5)}}else a.Td(Error("Waiting for session status timed out."))},L7=function(a,b,c){H7.call(this,a,b,"DialSession");
this.o=this.F=null;this.I="";this.N=c;this.A=null;this.D=g.Ha;this.B=NaN;this.J=(0,g.y)(this.uN,this);this.g=g.Ha},M7=function(a){a.g=a.G.tB(a.I,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ha;
this.Ln(b)},a),(0,g.y)(function(b){this.g=g.Ha;
this.Td(b)},a))},N7=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.A){var c=a.A.currentTime||0;b.v=a.A.videoId;b.t=c}H5()&&(b.env_useStageMdx=1);return g.Cf(b)},O7=function(a,b){H7.call(this,a,b,"ManualSession");
this.g=g.Xo((0,g.y)(this.ki,this,null),150)},P7=function(a,b,c,d){g.O.call(this);
this.i=a;this.D=b||"233637DE";this.B=c||"cl";this.F=d||!1;this.g=null;this.A=!1;this.l=[];this.o=(0,g.y)(this.xK,this)},Q7=function(a,b){return b?g.Ya(a.l,function(c){return o5(b,c.label)},a):null},R7=function(a){k7("Controller",a)},g7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},S7=function(a){return a.A||!!a.l.length||!!a.g},T7=function(a,b,c){b!=a.g&&(g.Bi(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.i):a.O("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.vz,a,b)),b.l?a.O("yt-remote-cast2-session-change",b.l):c&&a.g.ki(null)):a.O("yt-remote-cast2-session-change",null))},U7=function(a){var b=a.i.sB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&o5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Q7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Sqa=function(a,b,c,d,e,f,k){Pqa()?Qqa(b,e,f,k)&&(W7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?X7(a,c):(window.__onGCastApiAvailable=function(l,m){l?X7(a,c):(Y7("Failed to load cast API: "+m),Z7(!1),W7(!1),w5("yt-remote-cast-available"),w5("yt-remote-cast-receiver"),$7(),c(!1))},d?g.jp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?wqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?M5():(N5(),L5(Rqa.map(uqa))))):V7("Cannot initialize because not running Chrome")},$7=function(){V7("dispose");
var a=a8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);b8(!1);g.ep(c8);c8.length=0},d8=function(){return!!g.Cs("yt-remote-cast-installed")},e8=function(){var a=g.Cs("yt-remote-cast-receiver");
return a?a.friendlyName:null},f8=function(){V7("clearCurrentReceiver");
w5("yt-remote-cast-receiver")},g8=function(){return d8()?a8()?a8().getCastSession():(Y7("getCastSelector: Cast is not initialized."),null):(Y7("getCastSelector: Cast API is not installed!"),null)},i8=function(){d8()?a8()?h8()?(V7("Requesting cast selector."),a8().requestSession()):(V7("Wait for cast API to be ready to request the session."),c8.push(g.dp("yt-remote-cast2-api-ready",i8))):Y7("requestCastSelector: Cast is not initialized."):Y7("requestCastSelector: Cast API is not installed!")},j8=function(a,
b){h8()?a8().setConnectedScreenStatus(a,b):Y7("setConnectedScreenStatus called before ready.")},Pqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.ow||a},Tqa=function(a,b){a8().init(a,b)},Qqa=function(a,b,c,d){var e=!1;
a8()||(a=new P7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Bs("yt-remote-cast-available",f);l5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){V7("onReceiverSelected: "+f.friendlyName);
g.Bs("yt-remote-cast-receiver",f);l5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){V7("onReceiverResumed: "+f.friendlyName);
g.Bs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){V7("onSessionChange: "+r5(f));
f||w5("yt-remote-cast-receiver");l5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
V7("cloudview.createSingleton_: "+e);return e},a8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},X7=function(a,b){Z7(!0);
W7(!1);Tqa(a,function(c){c?(b8(!0),g.gp("yt-remote-cast2-api-ready")):(Y7("Failed to initialize cast API."),Z7(!1),w5("yt-remote-cast-available"),w5("yt-remote-cast-receiver"),$7());b(c)})},V7=function(a){k7("cloudview",a)},Y7=function(a){k7("cloudview",a)},Z7=function(a){V7("setCastInstalled_ "+a);
g.Bs("yt-remote-cast-installed",a)},h8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},b8=function(a){V7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},W7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},k8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.B=this.D=0;this.g=null;this.hasNext=this.Me=!1;this.G=this.F=this.i=this.o=0;this.l=NaN;this.A=!1;this.reset(a)},l8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Me=!1;a.hasNext=!1;a.D=0;a.B=(0,g.D)();a.o=0;a.i=0;a.F=0;a.G=0;a.l=NaN;a.A=!1},m8=function(a){return 1==a.playerState?((0,g.D)()-a.B)/1E3:0},n8=function(a,b){a.D=b;
a.B=(0,g.D)()},o8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.B)/1E3+a.D;
case -1E3:return 0}return a.D},p8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&l8(a)},q8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Me;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.B;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.F;b.loadedTime=a.G;b.liveIngestionTime=a.l;return b},t8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.B=[];this.A=new Z6;this.l=this.i=null;this.G=(0,g.y)(this.tI,this);this.D=(0,g.y)(this.yk,this);this.F=(0,g.y)(this.sI,this);this.I=(0,g.y)(this.HI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Et,this),r8(this))):c=3;0!=c&&(b?this.Et(c):g.Xo((0,g.y)(function(){this.Et(c)},this),0));
var d=g8();d&&s8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},u8=function(a){return new k8(a.o.getPlayerContextData())},r8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.B.push(this.o.subscribe(b,g.Qa(this.uK,b),this))},a)},v8=function(a){(0,g.z)(a.B,function(b){this.o.unsubscribeByKey(b)},a);
a.B.length=0},w8=function(a,b){var c=a.A;
50>c.g.length+c.i.length&&a.A.i.push(b)},y8=function(a,b,c){var d=u8(a);
n8(d,c);-1E3!=d.playerState&&(d.playerState=b);x8(a,d)},z8=function(a,b,c){a.o.sendMessage(b,c)},x8=function(a,b){v8(a);
a.o.setPlayerContextData(q8(b));r8(a)},s8=function(a,b){a.l&&(a.l.removeUpdateListener(a.G),a.l.removeMediaListener(a.D),a.yk(null));
a.l=b;a.l&&(k7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.G),a.l.addMediaListener(a.D),a.l.media.length&&a.yk(a.l.media[0]))},A8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=u8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;n8(d,a.i.getEstimatedTime());x8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},B8=function(a,b,c){return(0,g.y)(function(d){this.Ib("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ib("Retrying "+b+" using MDx browser channel."),z8(this,b,c))},a)},C8=function(a,b,c){g.O.call(this);
this.A=NaN;this.J=!1;this.F=this.D=this.G=this.I=NaN;this.T=[];this.o=this.B=this.l=this.Oa=this.g=null;this.R=a;this.T.push(g.cr(window,"beforeunload",(0,g.y)(this.sD,this)));this.i=[];this.Oa=new k8;this.N=b.id;this.g=Uqa(this,c);this.g.subscribe("handlerOpened",this.xI,this);this.g.subscribe("handlerClosed",this.uI,this);this.g.subscribe("handlerError",this.vI,this);this.g.subscribe("handlerMessage",this.wI,this);Eqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.Ds()&&g.Bs("yt-remote-session-video-id",d)},this)},D8=function(a){k7("conn",a)},Uqa=function(a,b){return new a7(e7(a.R,"/bc"),b)},E8=function(a,b){a.O("proxyStateChange",b)},Vqa=function(a){a.A=g.Xo((0,g.y)(function(){D8("Connecting timeout");
this.Mh(1)},a),2E4)},F8=function(a){g.Zo(a.A);
a.A=NaN},G8=function(a){g.Zo(a.I);
a.I=NaN},Wqa=function(a){H8(a);
a.G=g.Xo((0,g.y)(function(){I8(this,"getNowPlaying")},a),2E4)},H8=function(a){g.Zo(a.G);
a.G=NaN},K8=function(a,b){b&&(F8(a),G8(a));
b==(c7(a.g)&&isNaN(a.A))?b&&(E8(a,1),I8(a,"getSubtitlesTrack")):b?(a.kw()&&a.Oa.reset(),E8(a,1),I8(a,"getNowPlaying"),J8(a)):a.Mh(1)},Xqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.O("remotePlayerChange"))},L8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;p8(a.Oa,c,d);a.O("remoteQueueChange")},Yqa=function(a,b){b.params=b.params||{};
L8(a,b);M8(a,b);a.O("autoplayDismissed")},M8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
n8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.G=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.F=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.A=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Wqa(a):H8(a);a.O("remotePlayerChange")},Zqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);n8(a.Oa,isNaN(c)?0:c);a.O("remotePlayerChange")}},$qa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.O("remotePlayerChange")},ara=function(a,b){a.B=b.params.videoId;
a.O("nowAutoplaying",parseInt(b.params.timeout,10))},bra=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Me="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.O("previousNextChange")},J8=function(a){g.Zo(a.F);
a.F=g.Xo((0,g.y)(a.Mh,a,1),864E5)},I8=function(a,b,c){c?D8("Sending: action="+b+", params="+g.rm(c)):D8("Sending: action="+b);
a.g.sendMessage(b,c)},N8=function(a){o7.call(this,"ScreenServiceProxy");
this.Wc=a;this.i=[];this.i.push(this.Wc.$_s("screenChange",(0,g.y)(this.pN,this)));this.i.push(this.Wc.$_s("onlineScreenChange",(0,g.y)(this.ZJ,this)))},gra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Po("MDX_CONFIG")||b;qqa();B5();O8||(O8=new d7(b?b.loungeApiHost:void 0),H5()&&(O8.g="/api/loungedev"));P8||(P8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",P8,void 0));cra();var c=Q8();if(!c){var d=new B7(O8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=Q8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Sqa(a,d,function(m){m?R8()&&j8(R8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){l5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),S8("Initializing: "+g.rm(b)),T8.push(g.dp("yt-remote-cast2-availability-change",function(){l5("yt-remote-receiver-availability-change")})),T8.push(g.dp("yt-remote-cast2-receiver-selected",function(){U8(null);
l5("yt-remote-auto-connect","cast-selector-receiver")})),T8.push(g.dp("yt-remote-cast2-receiver-resumed",function(){l5("yt-remote-receiver-resumed","cast-selector-receiver")})),T8.push(g.dp("yt-remote-cast2-session-change",dra)),T8.push(g.dp("yt-remote-connection-change",function(m){m?j8(R8(),"YouTube TV"):V8()||(j8(null,null),f8())})),a=W8(),b.isAuto&&(a.id+="#dial"),g.Lp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),S8(" -- with channel params: "+
g.rm(a)),era(a),c.start(),R8()||fra())},hra=function(){var a=X8();
d8()&&g.Cs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},X8=function(){var a=Q8().Wc.$_gos();
var b=Y8();b&&Z8()&&(u5(a,b)||a.push(b));return pqa(a)},$8=function(){var a=ira();
!a&&d8()&&e8()&&(a={key:"cast-selector-receiver",name:e8()});return a},ira=function(){var a=X8(),b=Y8();
b||(b=V8());return g.Ya(a,function(c){return b&&o5(b,c.key)?!0:!1})},Y8=function(){var a=R8();
if(!a)return null;var b=Q8().Qd();return v5(b,a)},dra=function(a){S8("remote.onCastSessionChange_: "+r5(a));
if(a){var b=Y8();b&&b.id==a.id?j8(b.id,"YouTube TV"):(b&&a9(),b9(a,1))}else Z8()&&a9()},a9=function(){h8()?a8().stopSession():Y7("stopSession called before API ready.");
var a=Z8();a&&(a.disconnect(1),c9(null))},d9=function(){var a=Z8();
return!!a&&3!=a.getProxyState()},S8=function(a){k7("remote",a)},Q8=function(){if(!e9){var a=g.x("yt.mdx.remote.screenService_");
e9=a?new N8(a):null}return e9},R8=function(){return g.x("yt.mdx.remote.currentScreenId_")},f9=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},jra=function(){return g.x("yt.mdx.remote.connectData_")},U8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},Z8=function(){return g.x("yt.mdx.remote.connection_")},c9=function(a){var b=Z8();
U8(null);a||f9("");g.Ga("yt.mdx.remote.connection_",a,void 0);P8&&((0,g.z)(P8,function(c){c(a)}),P8.length=0);
b&&!a?l5("yt-remote-connection-change",!1):!b&&a&&l5("yt-remote-connection-change",!0)},V8=function(){var a=g.Ds();
if(!a)return null;var b=Q8().Qd();return v5(b,a)},b9=function(a,b){Y8()&&Y8();
if(g9)h9=a;else{f9(a.id);var c=new C8(O8,a,W8());c.connect(b,jra());c.subscribe("beforeDisconnect",function(d){l5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){Z8()&&c9(null)});
c9(c)}},fra=function(){var a=V8();
a?(S8("Resume connection to: "+r5(a)),b9(a,0)):(F5(),f8(),S8("Skipping connecting because no session screen found."))},cra=function(){var a=W8();
if(g.Yb(a)){a=A5();var b=g.Cs("yt-remote-session-name")||"",c=g.Cs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},W8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},era=function(a){a?(g.Bs("yt-remote-session-app",a.app),g.Bs("yt-remote-session-name",a.name)):(w5("yt-remote-session-app"),w5("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.H.call(this);
this.A=a;this.i=b;this.l=new g.Or(this);g.J(this,this.l);this.l.L(b,"onCaptionsTrackListChanged",this.uJ);this.l.L(b,"captionschanged",this.rI);this.l.L(b,"captionssettingschanged",this.GA);this.l.L(b,"videoplayerreset",this.Mn);this.l.L(b,"mdxautoplaycancel",this.uC);this.R=this.l.L(b,"onVolumeChange",this.ez);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.qz,this);c.subscribe("remotePlayerChange",this.Ak,this);c.subscribe("remoteQueueChange",this.Mn,this);c.subscribe("autoplayUpNext",this.Ty,
this);c.subscribe("previousNextChange",this.nz,this);c.subscribe("nowAutoplaying",this.jz,this);c.subscribe("autoplayDismissed",this.Sy,this);this.suggestion=null;this.G=new g.NB(64);this.o=new g.K(this.EA,500,this);g.J(this,this.o);this.B=new g.K(this.FA,1E3,this);g.J(this,this.B);this.J=new O5(this.UM,0,this);g.J(this,this.J);this.D={};this.T=new g.K(this.gB,1E3,this);g.J(this,this.T);this.I=new g.dl(this.OF,1E3,this);g.J(this,this.I);this.N=g.Ha;this.GA();this.Mn();this.Ak()},j9=function(a,b){a.A.Mc(b,
a.i.getVideoData().lengthSeconds)},kra=function(a){j9(a,0);
a.o.stop();k9(a,new g.NB(64))},m9=function(a,b){if(l9(a)&&!a.F){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.vA(a.i.getVideoData(1).videoId,c);a.D=u8(a.g).g}},n9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Oe,h5(c));k9(a,new g.NB(1))},lra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{QQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.F=!1):(a.i.loadModule("captions"),a.F=!0)}else a.i.setOption("captions","track",{})},l9=function(a){return u8(a.g).videoId==a.i.getVideoData(1).videoId},k9=function(a,b){a.B.stop();
var c=a.G;if(!g.TB(c,b)){var d=g.U(b,2);d!=g.U(a.G,2)&&g.SJ(a.i,d);a.G=b;mra(a.A,c,b)}},o9=function(){g.W.call(this,{C:"div",
H:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{C:"div",H:"ytp-mdx-popup-dialog-inner-content",K:[{C:"div",H:"ytp-mdx-popup-title",U:"Jste odhl\u00e1\u0161eni"},{C:"div",H:"ytp-mdx-popup-description",U:"Videa, kter\u00e1 sledujete, mohou b\u00fdt p\u0159id\u00e1na do historie sledov\u00e1n\u00ed televize a\u00a0ovlivnit doporu\u010den\u00ed pro televizi. Pokud si to nep\u0159ejete, akci zru\u0161te a\u00a0p\u0159ihlaste se na YouTube na po\u010d\u00edta\u010di."},{C:"div",H:"ytp-mdx-privacy-popup-buttons",
K:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Zru\u0161it"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],U:"Potvrdit"}]}]}]});this.l=new g.MP(this,250);g.J(this,this.l);this.D=this.i["ytp-mdx-privacy-popup-cancel"];this.L(this.D,"click",this.o);this.A=this.i["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},p9=function(a){g.W.call(this,{C:"div",
H:"ytp-remote",K:[{C:"div",H:"ytp-remote-display-status",K:[{C:"div",H:"ytp-remote-display-status-icon",K:[g.aP()]},{C:"div",H:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.MP(this,250);g.J(this,this.l);this.o=a;this.L(a,"presentingplayerstatechange",this.A);nra(this,g.OJ(a))},nra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.$M("Chyba na za\u0159\u00edzen\u00ed $RECEIVER_NAME",c):g.UB(b)||g.U(b,4)?g.$M("P\u0159ehr\u00e1v\u00e1n\u00ed na za\u0159\u00edzen\u00ed $RECEIVER_NAME",c):g.$M("P\u0159ipojeno k\u00a0za\u0159\u00edzen\u00ed $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.vT.call(this,"P\u0159ehr\u00e1t na",0,a,b);
this.l=a;this.D={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},r9=function(a){g.sK.call(this,a);
this.i={key:t5(),name:"Tento po\u010d\u00edta\u010d"};this.A=null;this.o=[];this.I=this.g=null;this.F=[this.i];this.l=this.i;this.ik=new g.NB(64);this.J=0;this.Pm=-1;this.B=null;if(!g.ly(g.X(this.player))){a=this.player;var b=g.GC(a);b&&(b=b.tn())&&(b=new q9(a,b),g.J(this,b));b=new p9(a);g.J(this,b);g.cK(a,b.element,4);this.B=new o9;g.J(this,this.B);g.cK(a,this.B.element,4);this.G=!!V8()}this.D=null},s9=function(a){a.D&&(a.player.removeEventListener("presentingplayerstatechange",a.D),a.D=null)},mra=
function(a,b,c){a.ik=c;
a.player.O("presentingplayerstatechange",new g.YC(c,b))},t9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)a9();
else{var c;(c=!g.P(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.Po("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.Po("SESSION_INDEX")&&!g.Po("LOGGED_IN")))||a.G||!a.B);c||g.ly(g.X(a.player))||(g.UB(g.OJ(a.player))?a.player.pauseVideo():(a.D=(0,g.y)(a.YL,a),a.player.addEventListener("presentingplayerstatechange",a.D)),a.B&&a.B.l.show(),Z8()||(g9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();
if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Oe,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=h5(c))&&(d.locationInfo=c);c=d}else c=null;S8("Connecting to: "+g.rm(b));"cast-selector-receiver"==b.key?(U8(c||null),h8()?a8().setLaunchParams(c||null):Y7("setLaunchParams called before ready.")):!c&&d9()&&R8()==b.key?l5("yt-remote-connection-change",
!0):(a9(),U8(c||null),c=Q8().Qd(),(c=v5(c,b.key))&&b9(c,1))}},h6={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},g6={"'":"\\'"},ora={},nqa={ON:"atp",dQ:"ska",SP:"que",tP:"mus",cQ:"sus",LO:"dsp",ZP:"seq"};
m5.prototype.eg=function(){var a=new m5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var G5,z5="",vqa=I5("loadCastFramework")||I5("loadCastApplicationFramework"),Rqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(O5,g.H);g.h=O5.prototype;g.h.nD=function(a){this.o=arguments;this.g=!1;this.Da?this.l=(0,g.D)()+this.Xc:this.Da=g.bl(this.A,this.Xc)};
g.h.stop=function(){this.Da&&(g.w.clearTimeout(this.Da),this.Da=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.B.apply(null,this.o)))};
g.h.V=function(){this.stop();O5.eb.V.call(this)};
g.h.oD=function(){this.l?(this.Da=g.bl(this.A,this.l-(0,g.D)()),this.l=null):(this.Da=null,this.i?this.g=!0:(this.g=!1,this.B.apply(null,this.o)))};Q5.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
Q5.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};R5.prototype.g=null;R5.prototype.getOptions=function(){var a;(a=this.g)||(a={},T5(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var u9;g.Sa(S5,R5);u9=new S5;g.h=V5.prototype;g.h.Wg=null;g.h.Ce=!1;g.h.Si=null;g.h.Bt=null;g.h.Ci=null;g.h.Wh=null;g.h.Wf=null;g.h.Ag=null;g.h.oh=null;g.h.sc=null;g.h.dl=0;g.h.Ge=null;g.h.Eo=null;g.h.ng=null;g.h.Nj=-1;g.h.oA=!0;g.h.Lg=!1;g.h.yq=0;g.h.Vn=null;var b6={},$5={};g.h=V5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.hM=function(a){a=a.target;var b=this.Vn;b&&3==y6(a)?b.Jj():this.oB(a)};
g.h.oB=function(a){try{if(a==this.sc)a:{var b=y6(this.sc),c=this.sc.A,d=this.sc.getStatus();if(g.Jd&&!g.md(10)||g.Ld&&!g.kd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.bg&&!C6(this.sc))break a;this.Lg||4!=b||7==c||(8==c||0>=d?this.g.ze(3):this.g.ze(2));l6(this);var e=this.sc.getStatus();this.Nj=e;var f=C6(this.sc);(this.Ce=200==e)?(4==b&&d6(this),this.A?(f6(this,b,f),g.bg&&this.Ce&&3==b&&(this.ca.ea(this.i,"tick",this.bM),this.i.start())):c6(this,f),this.Ce&&!this.Lg&&(4==b?this.g.Jn(this):(this.Ce=
!1,Z5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ng=3,a6(13)):(this.ng=0,a6(14)),d6(this),e6(this))}}catch(k){this.sc&&C6(this.sc)}finally{}};
g.h.bM=function(){var a=y6(this.sc),b=C6(this.sc);this.dl<b.length&&(l6(this),f6(this,a,b),this.Ce&&4!=a&&Z5(this))};
g.h.xL=function(a){k6((0,g.y)(this.wL,this,a),0)};
g.h.wL=function(a){this.Lg||(l6(this),c6(this,a),Z5(this))};
g.h.yz=function(a){k6((0,g.y)(this.vL,this,a),0)};
g.h.vL=function(a){this.Lg||(d6(this),this.Ce=a,this.g.Jn(this),this.g.ze(4))};
g.h.cancel=function(){this.Lg=!0;d6(this)};
g.h.HL=function(){this.Si=null;var a=(0,g.D)();0<=a-this.Bt?(2!=this.Wh&&this.g.ze(3),d6(this),this.ng=2,a6(18),e6(this)):j6(this,this.Bt-a)};
g.h.getLastError=function(){return this.ng};g.h=p6.prototype;g.h.wq=null;g.h.Gd=null;g.h.Wn=!1;g.h.xw=null;g.h.fm=null;g.h.dr=null;g.h.xq=null;g.h.ge=null;g.h.Bf=-1;g.h.Mj=null;g.h.hj=null;g.h.connect=function(a){this.xq=a;a=q6(this.g,null,this.xq);a6(3);this.xw=(0,g.D)();var b=this.g.F;null!=b?(this.Mj=b[0],(this.hj=b[1])?(this.ge=1,r6(this)):(this.ge=2,t6(this))):(g5(a,"MODE","init"),this.Gd=new V5(this,void 0,void 0,void 0),this.Gd.Wg=this.wq,Y5(this.Gd,a,!1,null,!0),this.ge=0)};
g.h.vC=function(a){if(a)this.ge=2,t6(this);else{a6(4);var b=this.g;b.Le=b.dg.Bf;W6(b,9)}a&&this.ze(2)};
g.h.Pp=function(a){return this.g.Pp(a)};
g.h.abort=function(){this.Gd&&(this.Gd.cancel(),this.Gd=null);this.Bf=-1};
g.h.ww=function(){return!1};
g.h.rz=function(a,b){this.Bf=a.Nj;if(0==this.ge)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Le=this.Bf;W6(c,2);return}this.Mj=c[0];this.hj=c[1]}else c=this.g,c.Le=this.Bf,W6(c,2);else if(2==this.ge)if(this.Wn)a6(7),this.dr=(0,g.D)();else if("11111"==b){if(a6(6),this.Wn=!0,this.fm=(0,g.D)(),c=this.fm-this.xw,!g.Jd||g.md(10)||500>c)this.Bf=200,this.Gd.cancel(),a6(12),s6(this.g,this,!0)}else a6(8),this.fm=this.dr=(0,g.D)(),this.Wn=!1};
g.h.Jn=function(){this.Bf=this.Gd.Nj;if(this.Gd.Ce)0==this.ge?this.hj?(this.ge=1,r6(this)):(this.ge=2,t6(this)):2==this.ge&&((!g.Jd||g.md(10)?!this.Wn:200>this.dr-this.fm)?(a6(11),s6(this.g,this,!1)):(a6(12),s6(this.g,this,!0)));else{0==this.ge?a6(9):2==this.ge&&a6(10);var a=this.g;this.Gd.getLastError();a.Le=this.Bf;W6(a,2)}};
g.h.Pk=function(){return this.g.Pk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ze=function(a){this.g.ze(a)};g.Sa(u6,g.qk);var Aqa=/^https?$/i,pra=["POST","PUT"];g.h=u6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.A=0;this.Z=b;this.R=!1;this.i=!0;this.g=this.N?U5(this.N):U5(u9);this.T=this.N?this.N.getOptions():u9.getOptions();this.g.onreadystatechange=(0,g.y)(this.yw,this);try{k5(z6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){k5(z6(this,"Error opening Xhr: "+f.message));x6(this,f);return}a=c||"";
var e=this.headers.clone();d&&jqa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Pd(),zqa);c=g.w.FormData&&a instanceof g.w.FormData;!g.ab(pra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.S&&(this.g.withCredentials=this.S);try{B6(this),0<this.B&&(this.J=yqa(this.g),k5(z6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.J)),this.J?(this.g.timeout=this.B,this.g.ontimeout=(0,g.y)(this.zw,this)):this.G=g.bl(this.zw,this.B,this)),k5(z6(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){k5(z6(this,"Send error: "+f.message)),x6(this,f)}};
g.h.zw=function(){"undefined"!=typeof g.hY&&this.g&&(this.l="Timed out after "+this.B+"ms, aborting",this.A=8,z6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(z6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),w6(this))};
g.h.V=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),w6(this,!0));u6.eb.V.call(this)};
g.h.yw=function(){this.ga()||(this.aa||this.D||this.o?A6(this):this.wK())};
g.h.wK=function(){A6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<y6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.u(this.l)?this.l:String(this.l)};g.h=D6.prototype;g.h.vj=null;g.h.Cd=null;g.h.Rb=null;g.h.uq=null;g.h.hm=null;g.h.Hu=null;g.h.ym=null;g.h.vk=0;g.h.LH=0;g.h.Uc=null;g.h.lg=null;g.h.nf=null;g.h.Qg=null;g.h.dg=null;g.h.Co=null;g.h.ji=-1;g.h.ix=-1;g.h.Le=-1;g.h.Ph=0;g.h.Ih=0;g.h.Mg=8;var X6=new g.qk;g.Sa(E6,g.Sj);g.Sa(F6,g.Sj);g.Sa(G6,g.Sj);g.h=D6.prototype;g.h.connect=function(a,b,c,d,e){a6(0);this.uq=b;this.vj=c||{};d&&g.Da(e)&&(this.vj.OSID=d,this.vj.OAID=e);this.B?(k6((0,g.y)(this.bv,this,a),100),M6(this)):this.bv(a)};
g.h.bv=function(a){this.dg=new p6(this);this.dg.wq=null;this.dg.i=this.A;this.dg.connect(a)};
g.h.ww=function(){return 0==this.g};
g.h.xz=function(a){this.lg=null;R6(this,a)};
g.h.wz=function(){this.nf=null;this.Rb=new V5(this,this.l,"rpc",this.D);this.Rb.Wg=null;this.Rb.yq=0;var a=this.Hu.clone();e5(a,"RID","rpc");e5(a,"SID",this.l);e5(a,"CI",this.Co?"0":"1");e5(a,"AID",this.ji);I6(this,a);if(!g.Jd||g.md(10))e5(a,"TYPE","xmlhttp"),Y5(this.Rb,a,!0,this.ym,!1);else{e5(a,"TYPE","html");var b=this.Rb,c=!!this.ym;b.Wh=3;b.Wf=f5(a.clone());i6(b,c)}};
g.h.rz=function(a,b){if(0!=this.g&&(this.Rb==a||this.Cd==a))if(this.Le=a.Nj,this.Cd==a&&3==this.g)if(7<this.Mg){try{var c=this.A.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.nf){if(this.Rb)if(this.Rb.Ci+3E3<this.Cd.Ci)N6(this),this.Rb.cancel(),this.Rb=null;else break a;U6(this);a6(19)}}else this.ix=c[1],0<this.ix-this.ji&&37500>c[2]&&this.Co&&0==this.Ih&&!this.Qg&&(this.Qg=k6((0,g.y)(this.nI,this),6E3));else W6(this,11)}else b!=ora.mO.g&&W6(this,11);else if(this.Rb==a&&
N6(this),!g.wb(b)){c=this.A.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.ji=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.ym=e[2],e=e[3],null!=e?this.Mg=e:this.Mg=6,this.g=3,this.Uc&&this.Uc.Vu(),this.Hu=q6(this,this.Pk()?this.ym:null,this.uq),S6(this)):"stop"==e[0]&&W6(this,7):3==this.g&&("stop"==e[0]?W6(this,7):"noop"!=e[0]&&this.Uc&&this.Uc.Uu(e),this.Ih=0)}}};
g.h.nI=function(){null!=this.Qg&&(this.Qg=null,this.Rb.cancel(),this.Rb=null,U6(this),a6(20))};
g.h.Jn=function(a){if(this.Rb==a){N6(this);this.Rb=null;var b=2}else if(this.Cd==a)this.Cd=null,b=1;else return;this.Le=a.Nj;if(0!=this.g)if(a.Ce)1==b?(b=(0,g.D)()-a.Ci,X6.dispatchEvent(new F6(X6,a.oh?a.oh.length:0,b,this.Ph)),L6(this),this.o.length=0):S6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Le)){if(d=1==b)this.Cd||this.lg||1==this.g||2<=this.Ph?d=!1:(this.lg=k6((0,g.y)(this.xz,this,a),T6(this,this.Ph)),this.Ph++,d=!0);d=!(d||2==b&&U6(this))}if(d)switch(c){case 1:W6(this,
5);break;case 4:W6(this,10);break;case 3:W6(this,6);break;case 7:W6(this,12);break;default:W6(this,2)}}};
g.h.NC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.KM=function(a){a?a6(2):(a6(1),V6(this,8))};
g.h.Pp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new u6;a.S=!1;return a};
g.h.isActive=function(){return!!this.Uc&&this.Uc.isActive(this)};
g.h.ze=function(a){X6.dispatchEvent(new G6(X6,a))};
g.h.Pk=function(){return!(!g.Jd||g.md(10))};
g.h=Y6.prototype;g.h.Vu=function(){};
g.h.Uu=function(){};
g.h.Tu=function(){};
g.h.Cp=function(){};
g.h.Uv=function(){return{}};
g.h.isActive=function(){return!0};g.h=Z6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Vma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.Ec=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Sa($6,g.H);g.h=$6.prototype;g.h.pL=function(){this.Xc=Math.min(3E5,2*this.Xc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Xc+15E3*Math.random();g.tn(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Xc=5E3};g.Sa(a7,Y6);g.h=a7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Jf=function(a){return this.l.Xg(a)};
g.h.O=function(a,b){return this.l.O.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.Bi(this.l),b7(this),g.Bi(this.i),this.i=null)};
g.h.ga=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.G="";this.i.stop();this.A=a||null;this.o=b||0;a=this.I+"/test";b=this.I+"/bind";var d=new D6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.Uc=null);d.Uc=this;this.g=d;e?this.g.connect(a,b,this.B,e.l,e.ji):c?this.g.connect(a,b,this.B,c.sessionId,c.arrayId):this.g.connect(a,b,this.B)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):c7(this)&&O6(this.g,c)};
g.h.Vu=function(){this.i.reset();this.A=null;this.o=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)O6(this.g,a[b])}this.O("handlerOpened")};
g.h.Tu=function(a){var b=2==a&&401==this.g.Le;4==a||b||this.i.start();this.O("handlerError",a)};
g.h.Cp=function(a){if(!this.i.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Uv=function(){var a={v:2};this.G&&(a.gsessionid=this.G);0!=this.o&&(a.ui=""+this.o);0!=this.F&&(a.ui=""+this.F);this.A&&g.fc(a,this.A);return a};
g.h.Uu=function(a){"S"==a[0]?this.G=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),K6(this.g)):this.O("handlerMessage",new Cqa(a[0],a[1]))};
g.h.rM=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.Cd&&b++;0==b&&this.connect(this.A,this.o)};d7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
d7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
d7.prototype.A=function(a){a(Error("request timed out"))};var Iqa=(0,g.D)(),i7=null,m7=Array(50),l7=-1,n7=!1;g.Sa(o7,g.O);o7.prototype.Qd=function(){return this.g};
o7.prototype.contains=function(a){return!!u5(this.g,a)};
o7.prototype.get=function(a){return a?v5(this.g,a):null};
o7.prototype.info=function(a){k7(this.D,a)};g.t(q7,g.O);g.h=q7.prototype;g.h.start=function(){!this.g&&isNaN(this.Da)&&this.rB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Da)||(g.Zo(this.Da),this.Da=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.rB=function(){this.Da=NaN;this.g=g.Up(e7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.y)(this.nN,this),onError:(0,g.y)(this.mN,this),oe:(0,g.y)(this.oN,this)})};
g.h.nN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.O("pairingComplete",new n5(c))};
g.h.mN=function(a){this.g=null;a.status&&404==a.status?this.i>=qra.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=qra[this.i],this.Da=g.Xo((0,g.y)(this.rB,this),a),this.i++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.oN=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};
var qra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(s7,o7);g.h=s7.prototype;g.h.start=function(){r7(this)&&this.O("screenChange");!g.Cs("yt-remote-lounge-token-expiration")&&t7(this);g.Zo(this.i);this.i=g.Xo((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){r7(this);p7(this,a);u7(this,!1);this.O("screenChange");b(a);a.token||t7(this)};
g.h.remove=function(a,b){var c=r7(this);Kqa(this,a)&&(u7(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.yo=function(a,b,c,d){var e=r7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,u7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.V=function(){g.Zo(this.i);s7.eb.V.call(this)};
g.h.zD=function(a){r7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}u7(this,!b);b&&k7(this.D,"Missed "+b+" lounge tokens.")};
g.h.yD=function(a){k7(this.D,"Requesting lounge tokens failed: "+a)};g.t(w7,g.O);g.h=w7.prototype;g.h.start=function(){var a=parseInt(g.Cs("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?z7(this):(this.o=(0,g.D)()+3E5,g.Bs("yt-remote-fast-check-period",this.o),this.Fs())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){v7("Updating availability on schedule.");var a=this.B(),b=g.Lb(this.g,function(c,d){return c&&!!v5(a,d)},this);
y7(this,b)};
g.h.V=function(){g.Zo(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.Fs=function(){g.Zo(this.l);this.l=NaN;this.i&&this.i.abort();var a=A7(this);if(i5(a)){var b=e7(this.A,"/pairing/get_screen_availability");this.i=f7(this.A,b,{lounge_token:g.Sb(a).join(",")},(0,g.y)(this.SK,this,a),(0,g.y)(this.RK,this))}else y7(this,{}),z7(this)};
g.h.SK=function(a,b){this.i=null;var c=g.Sb(A7(this));if(g.rb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;y7(this,d);z7(this)}else this.Ib("Changing Screen set during request."),this.Fs()};
g.h.RK=function(a){this.Ib("Screen availability failed: "+a);this.i=null;z7(this)};
g.h.Ib=function(a){k7("OnlineScreenService",a)};g.Sa(B7,o7);g.h=B7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.O("screenChange"),this.i.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.yo=function(a,b,c,d){this.l.contains(a)?this.l.yo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.D,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.g:g.fb(this.g,(0,g.Vd)(this.o,function(b){return!this.contains(b)},this))};
g.h.sB=function(){return(0,g.Vd)(this.Qd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.tB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new q7(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.Bi(f);d(C7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Bi(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.qN=function(a,b,c,d){g.Up(e7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new n5(f.screen||{});if(!k.name||E7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);E7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(C7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
oe:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Bi(this.l);g.Bi(this.i);B7.eb.V.call(this)};
g.h.HD=function(){F7(this);this.O("screenChange");this.i.update()};
B7.prototype.dispose=B7.prototype.dispose;g.Sa(H7,g.O);g.h=H7.prototype;g.h.Ln=function(a){this.l=a;this.O("sessionScreen",this.l)};
g.h.Td=function(a){this.ga()||(a&&I7(this,""+a),this.l=null,this.O("sessionScreen",null))};
g.h.info=function(a){k7(this.T,a)};
g.h.vB=function(){return null};
g.h.Os=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){I7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Os("");H7.eb.V.call(this)};g.Sa(K7,H7);g.h=K7.prototype;g.h.Ns=function(a){if(this.g){if(this.g==a)return;I7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.B);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A)}this.g=a;this.g.addUpdateListener(this.B);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.A);Oqa(this)};
g.h.ki=function(a){this.info("launchWithParams no-op for Cast: "+g.rm(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Td()},this),(0,g.y)(function(){this.Td(Error("Failed to stop receiver app."))},this)):this.Td(Error("Stopping cast device witout session."))};
g.h.Os=g.Ha;g.h.V=function(){this.info("disposeInternal");g.Zo(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.B),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A));this.g=null;K7.eb.V.call(this)};
g.h.SL=function(a,b){if(!this.ga())if(b){var c=P5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.rm(c));switch(d){case "mdxSessionStatus":J7(this,c.screenId);break;default:I7(this,"Unknown youtube message: "+d)}}else I7(this,"Unable to parse message.")}else I7(this,"No data in message.")};
g.h.mw=function(a,b,c,d){D7(this.G,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(I7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Xo((0,g.y)(this.mw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.vB=function(){return this.g};
g.h.rN=function(a){this.ga()||a||(I7(this,"Cast session died."),this.Td())};g.Sa(L7,H7);g.h=L7.prototype;g.h.Ns=function(a){this.o=a;this.o.addUpdateListener(this.J)};
g.h.ki=function(a){this.A=a;this.D()};
g.h.stop=function(){this.g();this.g=g.Ha;g.Zo(this.B);this.o?this.o.stop((0,g.y)(this.Td,this,null),(0,g.y)(this.Td,this,"Failed to stop DIAL device.")):this.Td()};
g.h.V=function(){this.g();this.g=g.Ha;g.Zo(this.B);this.o&&this.o.removeUpdateListener(this.J);this.o=null;L7.eb.V.call(this)};
g.h.uN=function(a){this.ga()||a||(I7(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Td())};
g.h.Kq=function(a){this.I=t5();if(this.A){var b=new chrome.cast.DialLaunchResponse(!0,N7(this));a(b);M7(this)}else this.D=(0,g.y)(function(){g.Zo(this.B);this.D=g.Ha;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,N7(this));a(c);M7(this)},this),this.B=g.Xo((0,g.y)(function(){this.D()},this),100)};
g.h.cE=function(a,b,c){D7(this.G,this.F.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.Ln(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Kq(b,c)},this),(0,g.y)(function(d){I7(this,"Failed to get DIAL screen: "+d);
this.Kq(b,c)},this))};g.Sa(O7,H7);O7.prototype.stop=function(){this.Td()};
O7.prototype.Ns=g.Ha;O7.prototype.ki=function(){g.Zo(this.g);this.g=NaN;var a=v5(this.G.Qd(),this.i.label);a?this.Ln(a):this.Td(Error("No such screen"))};
O7.prototype.V=function(){g.Zo(this.g);this.g=NaN;O7.eb.V.call(this)};g.Sa(P7,g.O);g.h=P7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.y)(this.BK,this);c=new chrome.cast.ApiConfig(c,(0,g.y)(this.uz,this),f,d,e);c.customDialLaunchCallback=(0,g.y)(this.OI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.o),Fqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.uB,this)),this.l=U7(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(k){this.Ib("Failed to set initial custom receivers: "+g.rm(k))},this)),this.O("yt-remote-cast2-availability-change",S7(this)),b(!0))},this),(0,g.y)(function(k){this.Ib("Failed to initialize API: "+g.rm(k));
b(!1)},this))};
g.h.yM=function(a,b){R7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)R7("Unsetting old screen status: "+this.g.i.friendlyName),T7(this,null)}if(a&&b){if(!this.g){c=v5(this.i.Qd(),a);if(!c){R7("setConnectedScreenStatus: Unknown screen.");return}var d=Q7(this,c);d||(R7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.y)(function(e){this.Ib("Failed to set initial custom receivers: "+g.rm(e))},this)));
R7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);T7(this,new O7(this.i,d),!0)}this.g.Os(b)}else R7("setConnectedScreenStatus: no screen.")};
g.h.zM=function(a){this.ga()?this.Ib("Setting connection data on disposed cast v2"):this.g?this.g.ki(a):this.Ib("Setting connection data without a session")};
g.h.tN=function(){this.ga()?this.Ib("Stopping session on disposed cast v2"):this.g?(this.g.stop(),T7(this,null)):R7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.uz,this),(0,g.y)(this.YK,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.uB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.x("yt.mdx.remote.debug.handlers_")||[],g7);g.Bi(this.g);P7.eb.V.call(this)};
g.h.Ib=function(a){k7("Controller",a)};
g.h.vz=function(a,b){this.g==a&&(b||T7(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.xK=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),R7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)R7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{R7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.O("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:T7(this,
new O7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:T7(this,new L7(this.i,a,this.B));break;case chrome.cast.ReceiverType.CAST:T7(this,new K7(this.i,a));break;default:this.Ib("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Ib("Stopping receiver w/o session: "+a.friendlyName)}else this.Ib("onReceiverAction_ called without receiver.")};
g.h.OI=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ib("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Ib("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return R7("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ib('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);T7(this,new L7(this.i,b,this.B))}b=this.g;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.cE,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Kq,b))};
g.h.uz=function(a){if(!this.ga()){R7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)R7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),T7(this,new K7(this.i,b),!0);else{this.Ib("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=v5(this.i.Qd(),c.label);d&&o5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(R7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Bi(this.g),this.g=new K7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.vz,this,this.g)),this.g.ki(null));this.g.Ns(a)}}};
g.h.sN=function(){return this.g?this.g.vB():null};
g.h.YK=function(a){this.ga()||(this.Ib("Failed to estabilish a session: "+g.rm(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&T7(this,null))};
g.h.BK=function(a){R7("Receiver availability updated: "+a);if(!this.ga()){var b=S7(this);this.A=a==chrome.cast.ReceiverAvailability.AVAILABLE;S7(this)!=b&&this.O("yt-remote-cast2-availability-change",S7(this))}};
g.h.uB=function(){this.ga()||(this.l=U7(this),R7("Updating custom receivers: "+g.rm(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(){this.Ib("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",S7(this)))};
P7.prototype.setLaunchParams=P7.prototype.zM;P7.prototype.setConnectedScreenStatus=P7.prototype.yM;P7.prototype.stopSession=P7.prototype.tN;P7.prototype.getCastSession=P7.prototype.sN;P7.prototype.requestSession=P7.prototype.requestSession;P7.prototype.init=P7.prototype.init;P7.prototype.dispose=P7.prototype.dispose;var c8=[];k8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";l8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Me=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.B=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.F=a.duration,this.G=a.loadedTime,this.l=a.liveIngestionTime,this.A=
!isNaN(this.l))};
k8.prototype.isAdPlaying=function(){return 1081==this.playerState};
k8.prototype.getDuration=function(){return this.A?this.F+m8(this):this.F};
k8.prototype.clone=function(){return new k8(q8(this))};g.t(t8,g.O);g.h=t8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,B8(this,"play")):z8(this,"play"),y8(this,1,o8(u8(this))),this.O("remotePlayerChange")):w8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,B8(this,"pause")):z8(this,"pause"),y8(this,2,o8(u8(this))),this.O("remotePlayerChange")):w8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=u8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,B8(this,"seekTo",{newTime:a}))}else z8(this,"seekTo",{newTime:a});y8(this,3,a);this.O("remotePlayerChange")}else w8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,B8(this,"stopVideo")):z8(this,"stopVideo");var a=u8(this);a.index=-1;a.videoId="";l8(a);x8(this,a);this.O("remotePlayerChange")}else w8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=u8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Ib("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Ib("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);z8(this,"setVolume",e)}c.muted=b;c.volume=a;x8(this,c)}else w8(this,g.Qa(this.setVolume,a,b))};
g.h.vA=function(a,b){if(1==this.g){var c=u8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.rm(b.style),g.fc(d,c.g));z8(this,"setSubtitlesTrack",d);x8(this,c)}else w8(this,g.Qa(this.vA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();z8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=u8(this);d.audioTrackId=c;x8(this,d)}else w8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=u8(this);c=c||0;var m={videoId:a,currentIndex:c};p8(l,a,c);g.Da(b)&&(n8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.rm(k));z8(this,"setPlaylist",m);d||x8(this,l)};
g.h.Qn=function(a,b){if(1==this.g){if(a&&b){var c=u8(this);p8(c,a,b);x8(this,c)}z8(this,"previous")}else w8(this,g.Qa(this.Qn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=u8(this);p8(c,a,b);x8(this,c)}z8(this,"next")}else w8(this,g.Qa(this.nextVideo,a,b))};
g.h.zv=function(){1==this.g?z8(this,"dismissAutoplay"):w8(this,this.zv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){v8(this);this.o=null;this.A.clear();s8(this,null);g.O.prototype.V.call(this)};
g.h.Et=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.A.isEmpty();)b=a=this.A,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.uK=function(a,b){this.O(a,b)};
g.h.tI=function(a){if(!a)this.yk(null),s8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=u8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,x8(this,b)}};
g.h.yk=function(a){k7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.F);if(this.i=a)this.i.addUpdateListener(this.F),A8(this),this.O("remotePlayerChange")};
g.h.sI=function(a){a?(A8(this),this.O("remotePlayerChange")):this.yk(null)};
g.h.jt=function(){z8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.HI=function(){var a=g8();a&&s8(this,a)};
g.h.Ib=function(a){k7("CP",a)};g.t(C8,g.O);g.h=C8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;n8(this.Oa,m);this.o="UNSUPPORTED";D8("Connecting with setPlaylist and params: "+g.rm(l));this.g.connect({method:"setPlaylist",
params:g.rm(l)},a,C5())}else D8("Connecting without params"),this.g.connect({},a,C5());Vqa(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),E8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){F8(this);H8(this);G8(this);g.Zo(this.D);this.D=NaN;g.Zo(this.F);this.F=NaN;this.l=null;g.dr(this.T);this.T.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.B=this.i=this.Oa=this.g=null};
g.h.sD=function(){this.Mh(2)};
g.h.xI=function(){D8("Channel opened");this.J&&(this.J=!1,G8(this),this.I=g.Xo((0,g.y)(function(){D8("Timing out waiting for a screen.");this.Mh(1)},this),15E3));
tqa(Dqa(this.g),this.N)};
g.h.uI=function(){D8("Channel closed");isNaN(this.A)?F5(!0):F5();this.dispose()};
g.h.vI=function(a){F5();isNaN(this.Dj())?(D8("Channel error: "+a+" without reconnection"),this.dispose()):(this.J=!0,D8("Channel error: "+a+" with reconnection in "+this.Dj()+" ms"),E8(this,2))};
g.h.wI=function(a){a.params?D8("Received: action="+a.action+", params="+g.rm(a.params)):D8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=P5(a.params.devices);this.i=(0,g.B)(a,function(c){return new m5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
K8(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
K8(this,!1);break;case "remoteConnected":var b=new m5(P5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||gqa(this.i,b);
break;case "remoteDisconnected":b=new m5(P5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":L8(this,a);break;case "nowPlaying":Yqa(this,a);break;case "onStateChange":M8(this,a);break;case "onAdStateChange":Zqa(this,a);break;case "onVolumeChanged":$qa(this,a);break;case "onSubtitlesTrackChanged":Xqa(this,a);break;case "nowAutoplaying":ara(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.O("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.O("autoplayModeChange",this.o);"DISABLED"==this.o&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":bra(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:D8("Unrecognized action: "+a.action)}};
g.h.oM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&I8(this,"getNowPlaying")}};
g.h.hD=function(){var a=3;this.ga()||(a=0,isNaN(this.Dj())?c7(this.g)&&isNaN(this.A)&&(a=1):a=2);return a};
g.h.Mh=function(a){D8("Disconnecting with "+a);F8(this);this.O("beforeDisconnect",a);1==a&&F5();b7(this.g,a);this.dispose()};
g.h.gD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),p8(a,this.l,a.index));return q8(a)};
g.h.AM=function(a){var b=new k8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Zo(this.D),this.D=g.Xo((0,g.y)(this.oM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&o8(this.Oa)==o8(b)&&g.rm(this.Oa.g)==g.rm(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.O(d)},this)};
g.h.kw=function(){var a=this.g.B.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Dj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.aD=function(){return this.o||"UNSUPPORTED"};
g.h.bD=function(){return this.B||""};
g.h.lN=function(){if(!isNaN(this.Dj())){var a=this.g.i;g.un(a.g);a.start()}};
g.h.vM=function(a,b){I8(this,a,b);J8(this)};
C8.prototype.subscribe=C8.prototype.subscribe;C8.prototype.unsubscribeByKey=C8.prototype.Jf;C8.prototype.getProxyState=C8.prototype.hD;C8.prototype.disconnect=C8.prototype.Mh;C8.prototype.getPlayerContextData=C8.prototype.gD;C8.prototype.setPlayerContextData=C8.prototype.AM;C8.prototype.getOtherConnectedRemoteId=C8.prototype.kw;C8.prototype.getReconnectTimeout=C8.prototype.Dj;C8.prototype.getAutoplayMode=C8.prototype.aD;C8.prototype.getAutoplayVideoId=C8.prototype.bD;C8.prototype.reconnect=C8.prototype.lN;
C8.prototype.sendMessage=C8.prototype.vM;g.t(N8,o7);g.h=N8.prototype;g.h.Qd=function(a){return this.Wc.$_gs(a)};
g.h.contains=function(a){return!!this.Wc.$_c(a)};
g.h.get=function(a){return this.Wc.$_g(a)};
g.h.start=function(){this.Wc.$_st()};
g.h.add=function(a,b,c){this.Wc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Wc.$_r(a,b,c)};
g.h.yo=function(a,b,c,d){this.Wc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Wc.$_ubk(this.i[a]);this.i.length=0;this.Wc=null;o7.prototype.V.call(this)};
g.h.pN=function(){this.O("screenChange")};
g.h.ZJ=function(){this.O("onlineScreenChange")};
B7.prototype.$_st=B7.prototype.start;B7.prototype.$_gspc=B7.prototype.qN;B7.prototype.$_gsppc=B7.prototype.tB;B7.prototype.$_c=B7.prototype.contains;B7.prototype.$_g=B7.prototype.get;B7.prototype.$_a=B7.prototype.add;B7.prototype.$_un=B7.prototype.yo;B7.prototype.$_r=B7.prototype.remove;B7.prototype.$_gs=B7.prototype.Qd;B7.prototype.$_gos=B7.prototype.sB;B7.prototype.$_s=B7.prototype.subscribe;B7.prototype.$_ubk=B7.prototype.Jf;var h9=null,g9=!1,O8=null,P8=null,e9=null,T8=[];g.t(i9,g.H);g.h=i9.prototype;
g.h.V=function(){g.H.prototype.V.call(this);this.o.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.qz,this);this.g.unsubscribe("remotePlayerChange",this.Ak,this);this.g.unsubscribe("remoteQueueChange",this.Mn,this);this.g.unsubscribe("autoplayUpNext",this.Ty,this);this.g.unsubscribe("previousNextChange",this.nz,this);this.g.unsubscribe("nowAutoplaying",this.jz,this);this.g.unsubscribe("autoplayDismissed",this.Sy,this);this.g=this.A=null};
g.h.Ox=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!u8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==u8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Jj(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.rI=function(a){this.J.nD(a)};
g.h.UM=function(a){this.Ox("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.GA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||m9(this,a)};
g.h.ez=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.Ak,this);var b=Math.round(a.volume);a=!!a.muted;var c=u8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.T.start();this.g.subscribe("remotePlayerChange",this.Ak,this)}};
g.h.uJ=function(){g.Yb(this.D)||lra(this,this.D);this.F=!1};
g.h.qz=function(a,b){this.B.stop();2==b&&this.FA()};
g.h.Ak=function(){if(l9(this)){this.o.stop();var a=u8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.A.Pm=1;break;case 1082:case 1083:this.A.Pm=0;break;default:this.A.Pm=-1}switch(a.playerState){case 1081:case 1:k9(this,new g.NB(8));this.EA();break;case 1085:case 3:k9(this,new g.NB(9));break;case 1083:case 0:k9(this,new g.NB(2));this.I.stop();j9(this,this.i.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.NB(4));break;case 2:k9(this,new g.NB(4));j9(this,o8(a));
break;case -1:k9(this,new g.NB(64));break;case -1E3:k9(this,new g.NB(128,{errorCode:"mdx.remoteerror",errorMessage:"Toto video nen\u00ed k dispozici pro vzd\u00e1len\u00e9 p\u0159ehr\u00e1v\u00e1n\u00ed."}))}a=u8(this.g).g;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,lra(this,a));a=u8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.T.isActive()||this.gB()}else kra(this)};
g.h.nz=function(){this.i.O("mdxpreviousnextchange")};
g.h.Mn=function(){l9(this)||kra(this)};
g.h.uC=function(){this.g.zv()};
g.h.Ty=function(a){a&&(a=g.Up("/watch_queue_ajax",{method:"GET",sd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.AL,this)}))&&(this.N=(0,g.y)(a.abort,a))};
g.h.AL=function(a,b){var c=new g.wA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.O("mdxautoplayupnext",c)};
g.h.jz=function(a){isNaN(a)||this.i.O("mdxnowautoplaying",a)};
g.h.Sy=function(){this.i.O("mdxautoplaycanceled")};
g.h.OF=function(a,b){-1==u8(this.g).playerState?n9(this,a):b&&this.g.seekTo(a)};
g.h.gB=function(){if(l9(this)){var a=u8(this.g);this.l.Qa(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.L(this.i,"onVolumeChange",this.ez)}};
g.h.EA=function(){this.o.stop();if(!this.g.ga()){var a=u8(this.g);1==a.playerState&&k9(this,new g.NB(8));j9(this,o8(a));this.o.start()}};
g.h.FA=function(){this.B.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.B.start()};g.t(o9,g.W);o9.prototype.o=function(){l5("mdx-privacy-popup-cancel");this.l.hide()};
o9.prototype.B=function(){l5("mdx-privacy-popup-confirm");this.l.hide()};g.t(p9,g.W);p9.prototype.A=function(a){nra(this,a.state)};g.t(q9,g.vT);q9.prototype.J=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.D=g.tb(a,this.B,this),g.xT(this,(0,g.B)(a,this.B)),a=this.l.getOption("remote","currentReceiver"),this.me(this.B(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.B=function(a){return a.key};
q9.prototype.ye=function(a){return"cast-selector-receiver"==a?"Vys\u00edl\u00e1n\u00ed\u2026":this.D[a].name};
q9.prototype.Kc=function(a){g.vT.prototype.Kc.call(this,a);this.l.setOption("remote","currentReceiver",this.D[a]);this.o.kb()};g.t(r9,g.sK);g.h=r9.prototype;
g.h.create=function(){gra(g.cy(g.X(this.player)));this.o.push(g.dp("yt-remote-before-disconnect",this.oI,this));this.o.push(g.dp("yt-remote-connection-change",this.CK,this));this.o.push(g.dp("yt-remote-receiver-availability-change",this.oz,this));this.o.push(g.dp("yt-remote-auto-connect",this.AK,this));this.o.push(g.dp("yt-remote-receiver-resumed",this.zK,this));this.o.push(g.dp("mdx-privacy-popup-confirm",this.eM,this));this.o.push(g.dp("mdx-privacy-popup-cancel",this.dM,this));this.oz()};
g.h.load=function(){this.player.cancelPlayback();g.sK.prototype.load.call(this);this.A=new i9(this,this.player,this.g);var a=(a=jra())?a.currentTime:0;var b=d9()?new t8(Z8(),void 0):null;0==a&&b&&(a=o8(u8(b)));0!=a&&this.Mc(a);mra(this,this.ik,this.ik);g.zX(this.player.app,6)};
g.h.unload=function(){this.player.O("mdxautoplaycanceled");this.l=this.i;g.Ci(this.A,this.g);this.g=this.A=null;g.sK.prototype.unload.call(this);g.zX(this.player.app,5);s9(this)};
g.h.V=function(){g.ep(this.o);g.sK.prototype.V.call(this)};
g.h.af=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.A.Ox.apply(this.A,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Pm};
g.h.jD=function(){return this.loaded?this.A.suggestion:null};
g.h.Me=function(){return this.g?u8(this.g).Me:!1};
g.h.hasNext=function(){return this.g?u8(this.g).hasNext:!1};
g.h.Mc=function(a,b){this.J=a||0;this.player.O("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=u8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.l+m8(a):a.l,isAtLiveHead:1>=(a.A?a.i+m8(a):a.i)-this.getCurrentTime(),loaded:a.G,seekableEnd:a.A?a.i+m8(a):a.i,seekableStart:0<a.o?a.o+
m8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Qn=function(){this.g&&this.g.Qn()};
g.h.oI=function(a){1==a&&(this.I=this.g?u8(this.g):null)};
g.h.CK=function(){var a=d9()?new t8(Z8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.I=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Bi(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,o8(a)));this.player.O("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.oz=function(){this.F=[this.i].concat(hra());var a=$8()||this.i;t9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.YL=function(a){!this.G&&g.$C(a,8)&&(this.player.pauseVideo(),s9(this))};
g.h.AK=function(){var a=$8();t9(this,a)};
g.h.zK=function(){this.l=$8()};
g.h.eM=function(){this.G=!0;s9(this);g9=!1;h9&&b9(h9,1);h9=null};
g.h.dM=function(){this.G=!1;s9(this);t9(this,this.i);this.l=this.i;g9=!1;h9=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?i8():t9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&i8(),!0):!1}};
g.h.jt=function(){this.g.jt()};
g.h.Cb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.OU.remote=r9;})(_yt_player);
