---
new_page_extension: md
auto_deploy: false
admin_path: https://frontendisti.cz/superadmin
webhook_url: 
sections:
- type: heading
  label: CZ
- type: directory
  path: data/cz/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: data/cz/blog
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - blog-detail
- type: document
  path: data/cz/global.yml
  label: Global
- type: heading
  label: EN
- type: directory
  path: data/en/pages
  label: " EN - Pages"
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: data/en/blog
  label: EN - Blog
  create: documents
  match: "**/*"
  templates:
  - blog-detail
- type: document
  path: data/en/global.yml
  label: " EN - Global"
- type: heading
  label: General
- type: document
  path: data/all/translations.yml
  label: Translations
upload_dir: src/img/illust
public_path: "../img/illust"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: web
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/src"
  working_dir: "/src"
  instant_preview_command: npm run dev
