---
new_page_extension: md
auto_deploy: false
admin_path: https://frontendisti.cz/superadmin
webhook_url:
sections:
upload_dir: forestry
public_path: ""
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: web
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/src"
  working_dir: "/src"
  instant_preview_command: npm run dev
