backend:
  name: git-gateway
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true

media_folder: "src/img/illust" # Folder where user uploaded files should go
public_folder: "img/illust"

collections: # A list of collections the CMS should be able to edit
  - name: "meetup" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Meetup" # Used in the UI, ie.: "New Post"
    folder: "content/meetup" # The path to the folder where the documents are stored
    slug: "{{date}}-{{title}}"
    create: true # Allow users to create new documents in this collection
    format: json
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Venue", name: "venue", widget: "string"}
      - label: "Sponsors"
        name: "sponsors"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Url, name: url, widget: string, required: false}
          - {label: Avatar, name: avatar, widget: image, required: false}
          - label: "Avatar size"
            name: "avatarSize"
            widget: "list"
            fields:
              - {label: Width, name: width, widget: number}
              - {label: Height, name: height, widget: number}
      - label: "Talks"
        name: "talks"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Youtube, name: youtube, widget: string, required: false}
          - {label: Presentation, name: presentation, widget: string, required: false}
          - label: Speaker
            name: speaker
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Bio, name: bio, widget: string, required: false}
              - {label: Url, name: url, widget: string, required: false}
              - {label: Avatar, name: avatar, widget: image, required: false}
      - {label: "Youtube playlist", name: "youtubePlaylist", widget: "string", required: false}